### ISSUE TITLE
"--sh" does not work as expected in "rsuite docker ..." commands

### ISSUE THREAD

**Issue by freeyoung** [WLOGSolutions/RSuite#5]
**Describe the bug**

`--sh` only accepts the first string in its values if you have more than one strings.

**To Reproduce**

```
$ rsuite docker img --rver=3.5 -p debian --version 0.0.1 --sh="apt-get install libpq-dev"
```

**Expected behavior**

`apt-get install libpq-dev` is executed before the docker image gets built.

**Logs**

```
$ rsuite docker img --rver=3.5 -p debian --version 0.0.1 --sh="apt-get install libpq-dev"
ERROR: "install" is not a valid option, or does not support an argument
```

**Environment**
 - OS: macOS 10.14.4
 - RSuite/RSuiteCLI version: 0.36.252
 - R version: 3.6.0 (2019-04-26) -- "Planting of a Tree"

**Additional context**

I did some research on the `optparse` R library. It seems to be an incomplete copy of Python's `optparse` library, which has been deprecated for long. And as per [this SO](https://stackoverflow.com/questions/3839791/python-optparse-and-spaces-in-an-argument) said in the last answer:

> Optparse is not able to handle these situations (multiple strings). You can only use nargs to specify particular amount of valiables, but there is nothing like "one or more". You need to hack it or use different library (e.g. argparse or other).

I also checked the workarounds mentioned in other answers, but unfortunately, none of them worked:

- wrapping `apt-get install libpq-dev` with double or single quotes
- escaping the spaces like `apt-get\ install\ libpq-dev`
- `nargs`, which is not even a thing in R's clone of `optparse` ([docs here](https://www.rdocumentation.org/packages/optparse/versions/1.6.2/topics/make_option))

Then I happened to find that `argparse` [actually exists](https://github.com/trevorld/r-argparse) in the R world, and is even maintained by the author who wrote R's `optparse`. Surprisingly, it depends on Python:

> The package has a Python dependency.

That sounds a bit strange, but maybe it helps.

**Comment by ws171913** [comment]
Hello,

Sorry for not responding. Strange but I did not receive notification form github :(
Thant you for such a detailed and insightful report. 

Regarding the matter. I'll try to reproduce it. I'm pretty sure It worked some time ago. I've used that functionality.

Regarding optparse. It is definitly incomplete copy of Python package. Very simplistic one. But on the other side it has no dependencies. And that's why we use it instead of argparse. 

rsuite utility can install RSuite package, so it does not assume RSuite is installed at the first place. Even more it should be functional  without access to internet (the case of installation in corporate environment then RSuite is beeing installed from private repository). So it is crutial not to install to much just to use rsuite utility. Installation of Python or number of packages just to parse command line is absolutely not acceptable.

**Comment by ws171913** [comment]
I looked closer on the issue. 

Problem was in bash scripts: I used $* instead of $@ to pass command line parameters down for processing. $* interprets to match and parameters with spaces where splited onto separate arguments. 

I'm preparing new release. It will contain fix. Please check if it works properly and close the issue.

**Comment by WitJakuczun** [comment]
Can we close this one?

**Comment by WitJakuczun** [comment]
@freeyoung - can you close?
